name: Test and Lint

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: pipenv install --dev
      - name: Linter with pylint
        run: pipenv run pylint scraper
      - name: Run tests
        run: pipenv run pytest ./scraper/src -k "not _browser"
